/*
 Navicat Premium Data Transfer

 Source Server         : oracle-lmtplat-SCOTT-Lmt123456
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.0.7:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 22/05/2020 17:04:28
*/


-- ----------------------------
-- Table structure for SYS_CONFIG 对应 com.lc.pojo.SysConfig
-- ----------------------------
DROP TABLE "SCOTT"."SYS_CONFIG";
CREATE TABLE "SCOTT"."SYS_CONFIG" (
  "SC_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "KEY_NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "KEY_VALUE" VARCHAR2(500 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SYS_CONFIG"."SC_ORG_ID" IS '机构号';
COMMENT ON COLUMN "SCOTT"."SYS_CONFIG"."KEY_NAME" IS '设置健名';
COMMENT ON COLUMN "SCOTT"."SYS_CONFIG"."KEY_VALUE" IS '键值';

-- ----------------------------
-- Records of "SYS_CONFIG"
-- ----------------------------
INSERT INTO "SCOTT"."SYS_CONFIG" VALUES ('0000', 'AREANUMBER', '021001');
INSERT INTO "SCOTT"."SYS_CONFIG" VALUES ('0000', 'COPYRIGHTINFO', '罗美特(上海)自动化仪表股份有限公司');

-- ----------------------------
-- Checks structure for table SYS_CONFIG
-- ----------------------------
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0011704" CHECK ("SC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0012159" CHECK ("SC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0013875" CHECK ("SC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0013876" CHECK ("KEY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0071289" CHECK ("SC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SYS_CONFIG" ADD CONSTRAINT "SYS_C0071290" CHECK ("KEY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
